# fly.toml file generated for csopak-weather on 2022-05-23T19:47:19+02:00

app = "csopak-weather"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[deploy]
  release_command = "eval CsopakWeather.Release.migrate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  